language: csharp
solution: sharpDash.sln
install:
  - nuget restore sharpDash.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release sharpDash.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./sharpDashTests/bin/Release/sharpDashTests.dll